let suggestion =[

"Channel",
"Youtube",
"Facebook",
"Youtuber",
"Blogger",
"Bollywood",
"Vlogger",
"Freelancer",
"Developper",
"Nike",
"Adidas",
"Mbappe",
"Foot",
"Instagram",
"Web Designer",
"Sport",
"Rnb",
"Hp",
"Actualité",
"Marseille",
"Programmateur",
"Huawei",
"Bogota",
"Casa Del Papel",
"Nekfeu",
"Ninho",
"Banque Postal",
"Paris",
"Hamster",
"Freedom",
"Titeuf",
"Comment devenir un youtuber",
"Comment jouer à fortnite",
"Comment devenir un web developper",
"Comment cuire un jaune d'oeuf",
"Comment jouer au tennis",
"Comment créer un compte instagram",
"Pourquoi fait-il nuit?",
"Pourquoi nous transpirant?",
"Pourquoi l'eau douce et l'eau salé ne se rencontre pas",
"Pourquoi devons nous boire de l'eau?",
"Comment devenir un influenceur",
"Que veux dire le mot Monotonie",
"Yaya touré",
"Credit mutuel",
"Orange",
"Yahoo",
"Google",
"Kit kat",
"Lion",
"Saint etienne",
"Port de bouc",




];